---
stages:
- name: PREPARE
  inputs:
  - type: git
    branch: master
    service: ${NETWORK_REPO}
  triggers:
  - type: commit
  properties:
  - name: SCRIPT_DIR
    value: ${SCRIPT_DIR}
    type: text
  - name: BUILD_SCRIPTS
    value: ${BUILD_SCRIPTS}
    type: text
  jobs:
  - name: Prepare
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash
      source <(curl -sSL "https://raw.githubusercontent.com/hyperledger-composer-samples/lib/master/scripts/pipeline-PREPARE.sh")
